# Generated by Django 4.1.7 on 2024-01-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_wait",
            new_name="guest_can_pause",
        ),
    ]
